server:
  port: 7003

# Eureka 配置
eureka:
  instance:
    hostname: eureka7003.com # Eureka 服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # fetch-registry 如果为false，则表示自己为注册中心
    service-url:  # 与 Eureka 注册中心交互的地址，就是监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
